Mending: Initial state of 0.4, revision 1

diff --git a/Makefile.manual b/Makefile.manual
--- a/Makefile.manual
+++ b/Makefile.manual
@@ -1,4 +1,17 @@
 # Parts of the makefile that are not handled by automake
+
+###############
+# Fingerprint #
+###############
+
+# make snapshot of CVS state
+fingerprint.tbz:
+# make copies of all CVS state directories
+#   top_srcdir=${top_srcdir} sh ${top_srcdir}/batch/make/fingerprint
+	touch $@
+# later, you can uncompress it somewhere and do "./regenerate.sh" to regenerate the source tree
+# from CVS, so you have something to base your bugfixes on.
+
 ##################
 # Beautification #
 ##################
@@ -6,20 +19,20 @@
 # use this target if you're OK with the project's defaults and
 # want updated file timestamps
 rebeautify:
-#	ARTISTIC_STYLE_OPTIONS=$(srcdir)/config/astylerc sh $(srcdir)/batch/make/beautify -t $(srcdir) .beautytag.re
+	ARTISTIC_STYLE_OPTIONS=$(srcdir)/config/astylerc sh $(srcdir)/batch/make/beautify -t $(srcdir) .beautytag.re
 
 # use this target if you want to switch between your settings
 # (beautify-personal) and the project defaults to get back to
 # the defaults (timestamps stay untouched)
 beautify:
 	rm -f $(srcdir)/.beautytag.personal
-#	ARTISTIC_STYLE_OPTIONS=$(srcdir)/config/astylerc sh $(srcdir)/batch/make/beautify $(srcdir) .beautytag
+	ARTISTIC_STYLE_OPTIONS=$(srcdir)/config/astylerc sh $(srcdir)/batch/make/beautify $(srcdir) .beautytag
 
 # use this target to run astyle with your personal settings for
-# it (but remember to do "make beautify" before comitting to Subversion!)
+# it (but remember to do "make beautify" before comitting to CVS!)
 beautify-personal:
 	rm -f $(srcdir)/.beautytag $(srcdir)/.beautytag.re
-#	ARTISTIC_STYLE_OPTIONS=~/.astylerc sh $(srcdir)/batch/make/beautify $(srcdir) .beautytag.personal 
+	ARTISTIC_STYLE_OPTIONS=~/.astylerc sh $(srcdir)/batch/make/beautify $(srcdir) .beautytag.personal 
 
 ##########
 # Checks #
@@ -49,15 +62,13 @@ installcheck_install.%:
 
 #	delete old configuration and prune empty directories
 	rm -rf ._$*@oldvardir@
-	for d in `find ._$* -depth -type d`; do rmdir $$d; done > /dev/null 2>&1 || true
+	for d in `find ._$* -type d -depth`; do rmdir $$d; done > /dev/null 2>&1 || true
 
 #   move to final destination
 	mv -f ._$*$(destdir.$*)/* ._$*/ || true
 	rmdir ._$*$(destdir.$*) || true
 
-if USE_SYSINSTALL
 	test -r	._$*/@aa_localstatedir@/users.txt
-endif
 
 installcheck_run_%: installcheck_install_%
 	@echo "Testing executable..."
@@ -103,8 +114,13 @@ endif
 installcheck_douninstall.inst:
 	DESTDIR=`pwd`/._inst $(MAKE) uninstall
 
-installcheck_uninstall.inst: installcheck_test.inst
+installcheck_douninstall.inst2:
+	./._inst2/$(bindir)/${uninstaller}
 
+installcheck_douninstall.inst3:
+	./._inst3/$(bindir)/${uninstaller}
+
+installcheck_uninstall.inst: installcheck_test.inst
 installcheck_uninstall.%: installcheck_install.%
 	rm -rf ._$*/${localstatedir} ._$*/.doc ._$*/.help ._$*/leak.log ._$*/memprofile*.txt ._$*/gmon.out ._$*/@logdir@
 	$(MAKE) installcheck_douninstall.$*
@@ -113,64 +129,62 @@ installcheck_uninstall.%: installcheck_install.%
 	if test -s .leftover.$*; then cat .leftover.$*; false; else true; fi
 	rm -f .leftover.$*
 
-if USE_UNINSTALL
-installcheck_douninstall.inst2:
-	./._inst2/$(bindir)/${uninstaller}
-	find ._inst2 -mindepth 1 -type d -name ${progname} -exec echo leftover directory \{\} >> .leftover.inst2 \;
-
-installcheck_douninstall.inst3:
-	./._inst3/$(bindir)/${uninstaller}
-	find ._inst3 -mindepth 1 -type d -name ${progname} -exec echo leftover directory \{\} >> .leftover.inst3 \;
-
-myinstallcheck: installcheck_uninstall.inst installcheck_uninstall.inst2
-else
-myinstallcheck: installcheck_uninstall.inst
-endif
+installcheck: installcheck_uninstall.inst installcheck_uninstall.inst2
 	$(predistcheckclean)
 	@echo -e "\n---------------------------------------\nInstallation and uninstallation worked!\n---------------------------------------\n"
 
-installcheck: myinstallcheck
-devcheck: beautify myinstallcheck
-fullcheck: beautify devcheck distcheck
-
-# run all that don't require a full rebuild
-test: installcheck
-
-###############
-# Fingerprint #
-###############
-
-# initial rule for source change tag (make it really old)
-.changetag:
-	touch -t 9001010101 $@
-
-# make snapshot of SVN state, tracking relevant changes in .changetag
-fingerprint: .changetag
-# easy, just do svn info, that contains all the information needed. If that fails, try other scms.
-	svn info ${top_srcdir} > $@ || svk info ${top_srcdir} > $@ || { bzr testament ${top_srcdir}; bzr info ${top_srcdir};  } > $@ || echo "unknown" > $@
-	svn info `dirname ${top_srcdir}` >> @$ || svn info `dirname ${top_srcdir}` >> $@ || echo "unknown" >> $@
-	diff $@ .changetag > /dev/null 2>&1 || cp $@ .changetag
+cvscheck: beautify installcheck
+fullcheck: beautify cvscheck distcheck
 
 ########################
-# tracking changes     #
+# tracking CVS changes #
 ########################
 
-# change version on deliberate version edit
-$(srcdir)/version: $(wildcard $(srcdir)/*_version) .changetag
+# tag that will be newer than all CVS control files, thus being a good indicator for
+# official code changes that warrant version bumps or ChangeLog updates
+.cvsfiles:
+	touch $@
+#	rm -f $@
+#	touch -r $(srcdir)/ChangeLog $@
+#	for dir in $$(find $(srcdir) -name CVS | grep -v ". ."); do\
+#		echo -e .cvsfiles: $${dir}/Entries "\n" $${dir}/Entries: "\n\t@rm -f .cvsfiles" >> $@; \
+#	done
+
+ @silent_inc@ .cvsfiles
+
+# the version creation shell script only looks for changes of this directory, so
+# we update it as well
+$(srcdir)/CVS: .cvsfiles
+	test -r $@ && touch $@
+
+# Keeping version up to date,
+# but only touch it silently on real changes, and only when a distribution is built
+VERSIONDEPS=$(wildcard $(srcdir)/*_version) $(wildcard $(srcdir)/CVS)
+.version.new: $(VERSIONDEPS)
+	echo "m4_define(AUTOMATIC_VERSION,["`sh $(srcdir)/batch/make/version $(srcdir)`"])" > .version.new
+	if diff $@ ${srcdir}/version >/dev/null 2>&1; then :; else cp $@ ${srcdir}/version; fi
+
+# extra target to make before a real distribution is built
+distprep: .version.new
+# clear fingerprint
+#   if test -r ${srcdir}/CVS/Entries; then rm -f fingerprint.tbz; fi
+
+# change version on deliberate version edit anyway
+$(srcdir)/version: $(wildcard $(srcdir)/*_version)
 	echo "m4_define(AUTOMATIC_VERSION,["`sh $(srcdir)/batch/make/version $(srcdir)`"])" > $@
 
 # Keep the changelog up to date as well (triggered by make dist only)
-$(srcdir)/ChangeLog: .changetag
+$(srcdir)/ChangeLog: .cvsfiles
 	touch $@
-	@echo -e "\nGenerating ChangeLog from SVN/BZR, please be patient...\n"
-	cd ${srcdir}; svn log 2>&1 > ChangeLog || bzr log --gnu-changelog 2>&1 > ChangeLog || echo "No official releasse: no changelog" > ChangeLog
-	test -r $@ || touch $@
+#	rm -f $@
+#	@echo -e "\nGenerating ChangeLog from CVS, please be patient...\n"
+#	cd ${srcdir}; cvs2cl --follow-only b0_2_8_0 2>&1 || echo "No official releasse: no changelog" > ChangeLog
+#	test -r $@ || touch $@
 
-# extra target to make before a real distribution is built
-# triggers regeneration of ChangeLog and version
-distprep:
-# rebuild fingerprint and update source change tag that way
-	if test -d ${srcdir}/.svn; then rm -f fingerprint; $(MAKE) fingerprint; fi
+cvsclean:
+	rm -rf .cvsfiles .version.new
+
+clean-local: cvsclean
 
 #############
 # Debugging #
@@ -180,7 +194,7 @@ distprep:
 	echo "break st_Breakpoint()" > $@
 
 @progname@: all
-	test -r $@ || ln -sf src/armagetronad_main $@
+	ln -sf src/armagetronad_main $@
 
 DEBUGFILES=.gdbinit @progname@
 debug: $(DEBUGFILES)
diff --git a/batch/serverstarter.in b/batch/serverstarter.in
--- a/batch/serverstarter.in
+++ b/batch/serverstarter.in
@@ -2,19 +2,21 @@
 #
 # starts @progtitle@ from the installation directory and keeps it running
 
-[ X"${PIDDIR}" = X"" ] && PIDDIR=${HOME}/.@prognamebase@
-[ X"${VARDIR}" = X"" ] && VARDIR=${HOME}/.@prognamebase@/var
-[ X"${CONFIG}" = X"" ] && CONFIG=@aa_sysconfdir_reloc@
-[ X"${BINDIR}" = X"" ] && BINDIR=@prefix_reloc@/bin
+test "$PIDDIR" = "" && PIDDIR=$HOME/.@prognamebase@
+test "$VARDIR" = "" && VARDIR=$HOME/.@prognamebase@/var
+test "$BINDIR" = "" && BINDIR=@prefix_reloc@/bin
 
-echo $$ > ${PIDDIR}/@progname@-starter.pid
+echo $$ > $PIDDIR/@progname@-starter.pid
 
-cd ${VARDIR}
+pushd $VARDIR
 
-run() {
-    ${BINDIR}/@progname@ --configdir ${CONFIG} --userdatadir ${VARDIR} --daemon $* &
-    jobs -p > ${PIDDIR}/@progname@.pid
-    [ -s ${PIDDIR}/@progname@.pid ] || { echo "Warning: main program PID unavailable, server can't be stopped reliably."; echo $$ > ${PIDDIR}/@progname@.pid ; }
+declare -a STARTDATE_LOG
+
+function run()
+{
+    $BINDIR/@progname@@executable_suffix@ --userdatadir $VARDIR --daemon $* &
+    jobs -p > $PIDDIR/@progname@.pid
+    test -s $PIDDIR/@progname@.pid || { echo "Warning: main program PID unavailable, server can't be stopped reliably."; echo $$ > $PIDDIR/@progname@.pid ; }
     wait
     echo Terminated
 }
@@ -22,24 +24,26 @@ run() {
 while true; do
   STARTDATE=`date +%s`
 
-  run $*
+  run
 
   # give up if restarts come too quickly; ten per minute is suspicious
   OLDESTSTART=${STARTDATE_LOG[1]}
-  if [ ! -z "$OLDESTSTART" ]; then
-      TIMESPENT=`expr ${STARTDATE} - ${OLDESTSTART}`
-      if [ $TIMESPENT -lt 60 ]; then
+  if ! test -z "$OLDESTSTART"; then
+      TIMESPENT=$(($STARTDATE - $OLDESTSTART))
+      if test ${TIMESPENT} -lt 60; then
           echo "Stopping server, it is restarting too quickly."
-          rm -f ${PIDDIR}/@progname@-starter.pid
-          rm -f ${PIDDIR}/@progname@.pid
+          rm -f $PIDDIR/@progname@-starter.pid
+          rm -f $PIDDIR/@progname@.pid
+          popd
           exit
       fi
   fi
 
   # keep log of past start dates
-  for f in 1 2 3 4 5 6 7 8 9; do
-      next=`expr $f + 1`
+  for f in 1 2 3 4 5 6  7 8 9; do
+      next=$(( $f + 1 ))
       STARTDATE_LOG[$f]=${STARTDATE_LOG[$next]}
   done
   STARTDATE_LOG[10]=${STARTDATE}
 done
+popd
