copy bzr version logic from 0.4
It gives the same revision numbers as the git alpha versioning
scheme, unlike the primitive revno based scheme before.

diff --git a/batch/make/version b/batch/make/version
--- a/batch/make/version
+++ b/batch/make/version
@@ -95,34 +95,73 @@ fi
 
 # *TODO* once we get our superproject up on launchpad (and thus get saner branch nicks), use branch nicks for $major_version
 # Check if bzr is installed, and if the path is versionned
-bzr info ${srcdir} >/dev/null 2>&1
+bzr >/dev/null 2>&1
 # But for now, ignore it
-if test $? -eq 0
+if test $? -eq 0 && test -d ${srcdir}/.bzr
 #if test 1 -eq 0
 then
-    # get revno
-    revno=`bzr revno ${srcdir}`
+    # Crappily, we can't rely on revision numbers to do anything
+    # ( ie. when one merges then pushes, the last revno might be lower than originally)
+    # So we count revisions, including merged ones, also including fools which have empty
+    # lines with only "revno: 15" in their commit messages
+    revno=$( bzr revno ${srcdir} 2>/dev/null)    
+    revcount=$( bzr_count_revisions ${srcdir} )
+    lca=$revno
+    lcaz=$revcount
+    versioned=#
+    branchurl=$( bzr info ${srcdir} 2>/dev/null | sed -ne 's/^  parent branch: \(.*\)$/\1/p' )
 
+
+    # We will check this branch diverged, and/or if tree changed
+    bzrmissingcout=$( cd ${srcdir} && bzr missing --this 2>/dev/null )
+    missing=$?
     bzr diff ${srcdir} --quiet >/dev/null 2>&1
-    # Test for the return code of bzr diff (see bzr diff --help)
-    if test $? -eq 0
+    changed=$?
+        
+
+    if test ${missing} -eq 1
+    # if it diverged:
     then
-        # If no change was made, use revision number (with offset to match svn revno)
-        # but first check if it's tagged
+        # Count the revisions we added locally
+        localrevisions=$( echo "${bzrmissingcout}" | sed -ne '2,1s/[^0-9]//gp' )
+        # See how many steps it is, with the fool's number
+        stepsbackwards=$( bzr_count_revisions ${srcdir} ${localrevisions} )
+        # And start dancing.
+        minor_version=_alpha_z$(( ${revcount} - ${stepsbackwards} ))_${DATE}
+        # Set last common ancestors
+        lca=$(( ${revno} - ${localrevisions}))
+        lcaz=$(( ${revcount} - ${stepsbackwards} ))
+        srcchanged=#
+    elif test ${missing} -eq 0 && ( test ${changed} -eq 1 || test ${changed} -eq 2 )
+    then
+        # If a change was made and no more revision was added, just use revision fool's number plus build date
+        minor_version=_alpha_z${revcount}_${DATE}
+        # And this is versionned too
+        srcchanged=#
+    elif test ${missing} -eq 0
+    then
+        # If really no change was made, use the fool's number, with tag if any
+        # So check if we have tags
+        revno=$(bzr revno ${srcdir})
         tag=$(bzr tags -r $revno | awk '{ print $1 }')
-        if test $tag
+        if test ${tag}
         then
             # If it is tagged, use the tag
-            DATE=_$tag
+            minor_version=_alpha_z${revcount}_${tag}
         else
-            # If not, use revision number
-            DATE=_r${revno}
+            # If not, use fool's number only
+            minor_version=_alpha_z${revcount}
         fi
-    elif test $? -lt 3
+        # That's versioned as well
+    else
+        # Otherwise, this is just not versionned
+        versioned=
+    fi
+
+    if test $versioned
     then
-        # If a change was made, use revision number plus build date
-        DATE=_r${revno}_$DATE
-    # It returns 3 if it's not versionned, so forget it
+        branchnick=$( cd ${srcdir}; bzr nick )
+        revid=$( bzr testament | sed -ne 's/^revision-id: \(.*\)/\1/p' )
     fi
 fi
 
