Merge in revisions 1488 to 1505

diff --git a/batch/make/version b/batch/make/version
--- a/batch/make/version
+++ b/batch/make/version
@@ -8,126 +8,117 @@ srcdir="$1"
 
 # set version parts to defaults for CVS snapshot
 major_version=`cat ${srcdir}/major_version`
+minor_version_proto=`cat ${srcdir}/minor_version`
 DATE=`date +%Y%m%d`
 
 #echo $major_version
 #echo $minor_version
 
-if test -d "${srcdir}/CVS"; then
-    # get the date/branch/version tag
-    rawtag=`cat ${srcdir}/CVS/Entries | grep major_version | sed -e "s,/major_version/.*/.*/.*/,,"`
-    #echo $rawtag
-    # determine the type of the tag
-    echo $rawtag | grep "^D" > /dev/null && tagtype=D
-    #echo $rawtag | grep "^Tb" > /dev/null && tagtype=Tb
-    echo $rawtag | grep "^Tv" > /dev/null && tagtype=Tv
-    #echo $tagtype
+bzr_count_revisions()
+{
+    srcdir="$1"
+    limit="$2"
 
-    # extract the raw tag
-    tag=`echo $rawtag | sed -e "s,^$tagtype,,"`
-    #echo $tag
+    test -z "$limit" || limit="-l $limit"
 
-    # date tag: make it a date dagged alpha release
-    if test "$tagtype" = D; then
-        DATE=`echo $tag | sed -e "s,\...\...\...\$,," | sed -e "s,\.,,g"`
-        minor_version=`cat ${srcdir}/minor_version | sed -e "s,DATE,$DATE," -e "s,YYYYMMDD,$DATE,"`
-    fi
-
-    # version tag: take whole version, replace _[number] with .[number]
-    if test "$tagtype" = Tv; then
-        major_version=`echo $tag | sed -e "s,_\([0-9]\),\.\\1,g"`
-        minor_version=""
-        DATE=""
-    fi
-fi
-
-if test -d "${srcdir}/.svn" || test -d "${srcdir}/../.svn"; then
-    # get the inter-repository path by parsing the URL
-
-    URL=`svn info ${srcdir} | grep ^URL | sed -e 's,^URL: ,,'`
-
-    # uncomment the followint URLs to test various cases
-    # trunk
-    # URL=https://svn.sourceforge.net/svnroot/armagetronad/armagetronad/trunk/armagetronad
-    # branch 0.4
-    # URL=https://svn.sourceforge.net/svnroot/armagetronad/armagetronad/branches/0.4/armagetronad
-
-    # tag 0.2.8.2
-    # URL=https://svn.sourceforge.net/svnroot/armagetronad/armagetronad/tags/0.2.8.2/armagetronad
-
-    #echo URL=$URL
-    REPOPATH=`echo $URL | sed -e 's,/armagetronad$,,' -e 's,.*/armagetronad/,,'`
-    #echo REPOPATH=$REPOPATH
-
-    # is it a tag?
-    if echo $REPOPATH | grep '^tags/' > /dev/null; then
-        # echo Tag
-        major_version=`echo $REPOPATH | sed -e 's,^tags/,,'`
-        minor_version=""
-        DATE=""
-    else
-        # make revision the alpha tag
-        REVISION=`svn info ${srcdir} | grep ^Revision | sed -e 's,^Revision: ,,'`
-
-        # is it a branch?
-        if echo $REPOPATH | grep '^branches/' > /dev/null; then
-            # echo Branch
-            branch=`echo $REPOPATH | sed -e 's,^branches/,,'`
-            # branch 0.2.8 produces 0.2.9 versions. Confusing, yeah, but moving it
-            # in the repo is too risky.
-            if test ${branch} = "0.2.8"; then
-                # try to get revision ID from bzr using the magic bzr-svn marker
-                # (only works this way on 0.2.8)
-                REVISION=`svn propget bzr:revision-id:v3-list-QlpoOTFBWSZTWZvbKhsAAAdRgAAQABK6798QIABURMgAAaeoNT1TxT1DQbKaeobXKiyAmlWT7Y5MkdJOtXDtB7w7DOGFBHiOBxaUIu7HQyyQSvxdyRThQkJvbKhs ${srcdir} | tail -n 4 | sed -e 's, .*,,' | grep [0-9] | tail -n 1`
-            else
-                major_version=${branch}
-            fi
-        fi
-        
-        # trunk or branch
-
-        #echo REVISION=$REVISION
-        minor_version=_alpha_r$REVISION
-        DATE=""
-    fi
-fi
+    count=$(bzr log --include-merges --line $limit "${srcdir}" 2>/dev/null | wc -l)
+    echo $count
+}
 
 # *TODO* once we get our superproject up on launchpad (and thus get saner branch nicks), use branch nicks for $major_version
 # Check if bzr is installed, and if the path is versionned
-bzr info ${srcdir} >/dev/null 2>&1
+bzr >/dev/null 2>&1
 # But for now, ignore it
-if test $? -eq 0
+if test $? -eq 0 && test -d ${srcdir}/.bzr
 #if test 1 -eq 0
 then
-    # get revno
-    revno=`bzr revno ${srcdir}`
+    # Crappily, we can't rely on revision numbers to do anything
+    # ( ie. when one merges then pushes, the last revno might be lower than originally)
+    # So we count revisions, including merged ones, also including fools which have empty
+    # lines with only "revno: 15" in their commit messages
+    revno=$( bzr revno ${srcdir} 2>/dev/null)    
+    revcount=$( bzr_count_revisions ${srcdir} )
+    lca=$revno
+    lcaz=$revcount
+    versioned=#
+    branchurl=$( bzr info ${srcdir} 2>/dev/null | sed -ne 's/^  parent branch: \(.*\)$/\1/p' )
 
+
+    # We will check this branch diverged, and/or if tree changed
+    bzrmissingcout=$( cd ${srcdir} && bzr missing --this 2>/dev/null )
+    missing=$?
     bzr diff ${srcdir} --quiet >/dev/null 2>&1
-    # Test for the return code of bzr diff (see bzr diff --help)
-    if test $? -eq 0
+    changed=$?
+        
+
+    if test ${missing} -eq 1
+    # if it diverged:
     then
-        # If no change was made, use revision number (with offset to match svn revno)
-        # but first check if it's tagged
+        # Count the revisions we added locally
+        localrevisions=$( echo "${bzrmissingcout}" | sed -ne '2,1s/[^0-9]//gp' )
+        # See how many steps it is, with the fool's number
+        stepsbackwards=$( bzr_count_revisions ${srcdir} ${localrevisions} )
+        # And start dancing.
+        minor_version=_alpha_z$(( ${revcount} - ${stepsbackwards} ))_${DATE}
+        # Set last common ancestors
+        lca=$(( ${revno} - ${localrevisions}))
+        lcaz=$(( ${revcount} - ${stepsbackwards} ))
+        srcchanged=#
+    elif test ${missing} -eq 0 && ( test ${changed} -eq 1 || test ${changed} -eq 2 )
+    then
+        # If a change was made and no more revision was added, just use revision fool's number plus build date
+        minor_version=_alpha_z${revcount}_${DATE}
+        # And this is versionned too
+        srcchanged=#
+    elif test ${missing} -eq 0
+    then
+        # If really no change was made, use the fool's number, with tag if any
+        # So check if we have tags
+        revno=$(bzr revno ${srcdir})
         tag=$(bzr tags -r $revno | awk '{ print $1 }')
-        if test $tag
+        if test ${tag}
         then
             # If it is tagged, use the tag
-            DATE=_$tag
+            minor_version=_alpha_z${revcount}_${tag}
         else
-            # If not, use revision number
-            DATE=_r${revno}
+            # If not, use fool's number only
+            minor_version=_alpha_z${revcount}
         fi
-    elif test $? -lt 3
+        # That's versioned as well
+    else
+        # Otherwise, this is just not versionned
+        versioned=
+    fi
+
+    if test $versioned
     then
-        # If a change was made, use revision number plus build date
-        DATE=_r${revno}_$DATE
-    # It returns 3 if it's not versionned, so forget it
+        branchnick=$( cd ${srcdir}; bzr nick )
+        revid=$( bzr testament | sed -ne 's/^revision-id: \(.*\)/\1/p' )
+    fi
+fi
+
+if test -d "${srcdir}/.git"; then
+    # check for a tag
+    cd $srcdir
+    # todo: once we have make tags, consider just git describe --tags as version ID.
+    if tag=`git describe --tags --candidates=0` > /dev/null 2>&1; then
+        major_version=`echo ${tag} | sed -e s/version_// -e s/release_//`
+        minor_version=""
+        DATE=""
+    else
+        if git diff-index --quiet HEAD --; then
+            # local checkout clean, just use revno
+            DATE=_z`git rev-list HEAD --count`
+        else
+            # local changes, add date
+            DATE=_z`git rev-list HEAD --count`_$DATE
+        fi
     fi
 fi
 
 if test -z "$minor_version"
 then
-    test -z "$DATE" || minor_version=`cat ${srcdir}/minor_version | sed -e "s,DATE,$DATE," -e "s,YYYYMMDD,$DATE,"`
+    test -z "$DATE" || minor_version=`echo ${minor_version_proto} | sed -e "s,DATE,$DATE," -e "s,YYYYMMDD,$DATE,"`
 fi
 
 echo $major_version$minor_version
